package medicinefollowupproject;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Polygon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author merve
 */
public class AboutUs extends javax.swing.JFrame {

    /**
     * Creates new form AboutUs
     */
    public AboutUs() {
        initComponents();
        this.setLocationRelativeTo(null);

        setInfo();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

    }
//ShowInfoOfCompany generic class'ımdan yararlanarak framedeki textArea kısımlarına bilgileri yerleştirdim.

    public void setInfo() {
        ShowInfoOfCompany<String> showString = new ShowInfoOfCompany<>("This applications works for you. Everyone has so-\n"
                + "me healthy problems so you can use this applica-\n"
                + "tion. This application produces by our engineers \n"
                + "on 1989. Have a healthy day.");
        showString.print(txtAreaAboutApp);

        ShowInfoOfCompany<Integer> showNumberInfoOfCompany = new ShowInfoOfCompany<>(4445566);
        showNumberInfoOfCompany.print((txtAreaCompanyNum));

        ShowInfoOfCompany<Integer> showNumberInfoOfCustomerServices = new ShowInfoOfCompany<>(0212344343);
        showNumberInfoOfCustomerServices.print((txtAreaServices));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        feedbackDialog = new javax.swing.JDialog();
        pnlFeedback = new javax.swing.JPanel();
        btnLovedApp = new javax.swing.JCheckBox();
        yes_no_icon = new javax.swing.JLabel();
        btnLovedDesign = new javax.swing.JCheckBox();
        btnAppHelpedMe = new javax.swing.JCheckBox();
        btnGiveFeedback = new javax.swing.JButton();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        pnlAboutUs = new javax.swing.JPanel();
        labelTitle = new javax.swing.JLabel();
        btnFeedback = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaAboutApp = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaCompanyNum = new javax.swing.JTextArea();
        labelAboutApp = new javax.swing.JLabel();
        labelCompanyNumbers = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAreaServices = new javax.swing.JTextArea();
        labelCustomServices = new javax.swing.JLabel();

        pnlFeedback.setBackground(new java.awt.Color(255, 255, 255));

        btnLovedApp.setText("I LOVED THE APPLİCATİON");

        yes_no_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rating.png"))); // NOI18N

        btnLovedDesign.setText("I LOVED THE DESİGN OF THİS APPLİCATİON");

        btnAppHelpedMe.setText("THİS APPLİCATİON HELP ME A LOT");

        btnGiveFeedback.setText("GİVE A FEEDBACK");
        btnGiveFeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGiveFeedbackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlFeedbackLayout = new javax.swing.GroupLayout(pnlFeedback);
        pnlFeedback.setLayout(pnlFeedbackLayout);
        pnlFeedbackLayout.setHorizontalGroup(
            pnlFeedbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFeedbackLayout.createSequentialGroup()
                .addGroup(pnlFeedbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFeedbackLayout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(yes_no_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlFeedbackLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(pnlFeedbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLovedDesign)
                            .addComponent(btnLovedApp)
                            .addComponent(btnAppHelpedMe)
                            .addComponent(btnGiveFeedback))))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        pnlFeedbackLayout.setVerticalGroup(
            pnlFeedbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFeedbackLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(yes_no_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLovedApp)
                .addGap(29, 29, 29)
                .addComponent(btnLovedDesign)
                .addGap(33, 33, 33)
                .addComponent(btnAppHelpedMe)
                .addGap(41, 41, 41)
                .addComponent(btnGiveFeedback)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout feedbackDialogLayout = new javax.swing.GroupLayout(feedbackDialog.getContentPane());
        feedbackDialog.getContentPane().setLayout(feedbackDialogLayout);
        feedbackDialogLayout.setHorizontalGroup(
            feedbackDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFeedback, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        feedbackDialogLayout.setVerticalGroup(
            feedbackDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFeedback, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jMenuItem1.setText("Main Page");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlAboutUs.setBackground(new java.awt.Color(255, 255, 255));
        pnlAboutUs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlAboutUsMouseClicked(evt);
            }
        });

        labelTitle.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        labelTitle.setText("ABOUT US");

        btnFeedback.setText("FEEDBACK WİTH US ");
        btnFeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFeedbackActionPerformed(evt);
            }
        });

        txtAreaAboutApp.setEditable(false);
        txtAreaAboutApp.setColumns(20);
        txtAreaAboutApp.setRows(5);
        txtAreaAboutApp.setText("This applications works for you. Everyone has so-\nme healthy problems so you can use this applica-\ntion. This application produces by our engineers \non 1989. Have a healthy day.");
        jScrollPane1.setViewportView(txtAreaAboutApp);

        txtAreaCompanyNum.setEditable(false);
        txtAreaCompanyNum.setColumns(20);
        txtAreaCompanyNum.setRows(5);
        jScrollPane2.setViewportView(txtAreaCompanyNum);

        labelAboutApp.setForeground(new java.awt.Color(0, 153, 153));
        labelAboutApp.setText("About Application");

        labelCompanyNumbers.setForeground(new java.awt.Color(0, 153, 153));
        labelCompanyNumbers.setText("Company Numbers");

        txtAreaServices.setEditable(false);
        txtAreaServices.setColumns(20);
        txtAreaServices.setRows(5);
        jScrollPane3.setViewportView(txtAreaServices);

        labelCustomServices.setForeground(new java.awt.Color(0, 153, 153));
        labelCustomServices.setText("Customer Services");

        javax.swing.GroupLayout pnlAboutUsLayout = new javax.swing.GroupLayout(pnlAboutUs);
        pnlAboutUs.setLayout(pnlAboutUsLayout);
        pnlAboutUsLayout.setHorizontalGroup(
            pnlAboutUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAboutUsLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(pnlAboutUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAboutUsLayout.createSequentialGroup()
                        .addGroup(pnlAboutUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelAboutApp, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFeedback))
                    .addGroup(pnlAboutUsLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(pnlAboutUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelCompanyNumbers, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelCustomServices, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlAboutUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addContainerGap(146, Short.MAX_VALUE))
        );
        pnlAboutUsLayout.setVerticalGroup(
            pnlAboutUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAboutUsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAboutUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFeedback))
                .addGap(18, 18, 18)
                .addComponent(labelAboutApp)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelCustomServices)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelCompanyNumbers)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAboutUs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAboutUs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//Kişinin uygulamayı ne kadar sevdiği ile ilgili bir feedback vermesini istedim.
    private void btnGiveFeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGiveFeedbackActionPerformed

        int selected = 0;
        if (btnLovedApp.isSelected()) {
            selected++;
        }
        if (btnLovedDesign.isSelected()) {
            selected++;
        }
        if (btnAppHelpedMe.isSelected()) {
            selected++;
        }
        switch (selected) {
            case 3:
                JOptionPane.showMessageDialog(rootPane, "We are so happy that you are content with this application  ", "THANK YOU FOR FEEDBACK", JOptionPane.INFORMATION_MESSAGE);
                break;
            case 2:
                JOptionPane.showMessageDialog(rootPane, "We will work hard for the propertie that you did not like", "THANK YOU FOR FEEDBACK", JOptionPane.INFORMATION_MESSAGE);
                break;
            case 1:
                JOptionPane.showMessageDialog(rootPane, "We will work hard for the properties that you did not like", "THANK YOU FOR FEEDBACK", JOptionPane.INFORMATION_MESSAGE);
                break;
            default:
                JOptionPane.showMessageDialog(rootPane, "PLEASE İNTERACT WİTH US: 444 66 35", "THANK YOU FOR FEEDBACK", JOptionPane.INFORMATION_MESSAGE);
                break;
        }
    }//GEN-LAST:event_btnGiveFeedbackActionPerformed
//Dialogu açtım.
    private void btnFeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFeedbackActionPerformed
        // TODO add your handling code here:
        feedbackDialog.setLocationRelativeTo(null);
        feedbackDialog.setSize(500, 500);
        feedbackDialog.setVisible(true);

    }//GEN-LAST:event_btnFeedbackActionPerformed
//Tıkladığım yerde popup menünün açılmasını sağladım
    private void pnlAboutUsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAboutUsMouseClicked
        // TODO add your handling code here:
        jPopupMenu1.setVisible(true);
        jPopupMenu1.show(this, evt.getX(), evt.getY());

    }//GEN-LAST:event_pnlAboutUsMouseClicked
//Main Page kısmına geçmeyi sağladım.
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        MainPage main = new MainPage();
        main.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox btnAppHelpedMe;
    private javax.swing.JButton btnFeedback;
    private javax.swing.JButton btnGiveFeedback;
    private javax.swing.JCheckBox btnLovedApp;
    private javax.swing.JCheckBox btnLovedDesign;
    private javax.swing.JDialog feedbackDialog;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelAboutApp;
    private javax.swing.JLabel labelCompanyNumbers;
    private javax.swing.JLabel labelCustomServices;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JPanel pnlAboutUs;
    private javax.swing.JPanel pnlFeedback;
    private javax.swing.JTextArea txtAreaAboutApp;
    private javax.swing.JTextArea txtAreaCompanyNum;
    private javax.swing.JTextArea txtAreaServices;
    private javax.swing.JLabel yes_no_icon;
    // End of variables declaration//GEN-END:variables
}
