package medicinefollowupproject;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author merve
 */
public class Patient extends javax.swing.JFrame {

    DefaultTableModel table;
    DefaultListModel list1 = new DefaultListModel();

    /**
     * Creates new form Patient
     */
    public Patient() {
        initComponents();
        table = (DefaultTableModel) prescribeInfosTable.getModel();
        listInfo.setModel(list1);
        showInformations();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }
//Tablo üzerinde dinamik arama yapmasını sağlayan methodu yazdım.

    public void search(String text) {
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(table);
        prescribeInfosTable.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(text));
    }

    public Patient(String name, String email, String password, String gender, int age, int id) {
        initComponents();
        table = (DefaultTableModel) prescribeInfosTable.getModel();
        listInfo.setModel(list1);

        labelNameData.setText(name);
        labelEmailData.setText(email);
        labelPassData.setText(password);
        labelGenderData.setText(gender);
        labelIdData.setText(String.valueOf(id));
        labelAgeData.setText(String.valueOf(age));
        showInformations();
    }
//Sisteme giriş yapan hastanın maili yardımıyla reçete bilgilerini alıp tabloya ekledim.

    final public void showInformations() {
        DataConnection connect = new DataConnection();
        String text = labelEmailData.getText();
        table.setRowCount(0);
        ArrayList<Prescribe> output = new ArrayList<Prescribe>();
        output = connect.showPatientsPrescribesOnTable(text);
        if (output != null) {
            for (Prescribe pres : output) {
                Object[] add = {pres.getDaily() + " " + pres.getWeekly() + " " + pres.getTime() + " " + pres.getHungry(), pres.getEmail(), pres.getMedicine(), pres.getBarcod(), pres.getDaily(), pres.getWeekly(), pres.getTime(), pres.getHungry(), pres.getDoctor()};
                table.addRow(add);
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        patientsPrescribeInfos = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        prescribeInfosTable = new javax.swing.JTable();
        txtSearchDynamic = new javax.swing.JTextField();
        labelSearch = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listInfo = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        patientPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        labelName = new javax.swing.JLabel();
        labelEmail = new javax.swing.JLabel();
        labelPass = new javax.swing.JLabel();
        labelGender = new javax.swing.JLabel();
        labelId = new javax.swing.JLabel();
        labelAge = new javax.swing.JLabel();
        womanIcon = new javax.swing.JLabel();
        menIcon = new javax.swing.JLabel();
        labelNameData = new javax.swing.JLabel();
        labelEmailData = new javax.swing.JLabel();
        labelPassData = new javax.swing.JLabel();
        labelGenderData = new javax.swing.JLabel();
        labelIdData = new javax.swing.JLabel();
        labelAgeData = new javax.swing.JLabel();
        btnShowPresInfos = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        jMenuItem1.setText("Main Page");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        patientsPrescribeInfos.setBackground(new java.awt.Color(0, 153, 153));

        prescribeInfosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Medicine Using Type", "Email", "Medicine", "Barcod"
            }
        ));
        prescribeInfosTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prescribeInfosTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(prescribeInfosTable);

        txtSearchDynamic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchDynamicKeyReleased(evt);
            }
        });

        labelSearch.setText("Dynamic search");

        jScrollPane2.setViewportView(listInfo);

        jLabel1.setText("İlaçlarını doğru zamanda minimum 2 saat ile ile içiniz!");

        javax.swing.GroupLayout patientsPrescribeInfosLayout = new javax.swing.GroupLayout(patientsPrescribeInfos.getContentPane());
        patientsPrescribeInfos.getContentPane().setLayout(patientsPrescribeInfosLayout);
        patientsPrescribeInfosLayout.setHorizontalGroup(
            patientsPrescribeInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patientsPrescribeInfosLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(patientsPrescribeInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, patientsPrescribeInfosLayout.createSequentialGroup()
                        .addComponent(labelSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtSearchDynamic, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(92, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, patientsPrescribeInfosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(patientsPrescribeInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );
        patientsPrescribeInfosLayout.setVerticalGroup(
            patientsPrescribeInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, patientsPrescribeInfosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(patientsPrescribeInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSearch)
                    .addComponent(txtSearchDynamic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(37, 37, 37))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 700));

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setMaximumSize(new java.awt.Dimension(700, 700));
        mainPanel.setPreferredSize(new java.awt.Dimension(700, 700));
        mainPanel.setSize(new java.awt.Dimension(700, 700));
        mainPanel.setLayout(new javax.swing.BoxLayout(mainPanel, javax.swing.BoxLayout.LINE_AXIS));

        patientPanel.setBackground(new java.awt.Color(255, 255, 255));
        patientPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("MY PRESCRİBE İNFORMATİONS"));
        patientPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                patientPanelMouseClicked(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(0, 153, 153));
        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 153));

        labelName.setBackground(new java.awt.Color(0, 153, 153));
        labelName.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        labelName.setForeground(new java.awt.Color(0, 153, 153));
        labelName.setText("MY NAME-SURNAME");

        labelEmail.setBackground(new java.awt.Color(0, 153, 153));
        labelEmail.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        labelEmail.setForeground(new java.awt.Color(0, 153, 153));
        labelEmail.setText("MY E-MAİL");

        labelPass.setBackground(new java.awt.Color(0, 153, 153));
        labelPass.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        labelPass.setForeground(new java.awt.Color(0, 153, 153));
        labelPass.setText("MY PASSWORD");

        labelGender.setBackground(new java.awt.Color(0, 153, 153));
        labelGender.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        labelGender.setForeground(new java.awt.Color(0, 153, 153));
        labelGender.setText("MY GENDER");

        labelId.setBackground(new java.awt.Color(0, 153, 153));
        labelId.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        labelId.setForeground(new java.awt.Color(0, 153, 153));
        labelId.setText("MY ID");

        labelAge.setBackground(new java.awt.Color(0, 153, 153));
        labelAge.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        labelAge.setForeground(new java.awt.Color(0, 153, 153));
        labelAge.setText("AGE");

        womanIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medicinefollowupproject/woman-2.png"))); // NOI18N

        menIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medicinefollowupproject/man.png"))); // NOI18N

        labelGenderData.setText("jLabel15");

        labelIdData.setText("jLabel16");

        labelAgeData.setText("jLabel18");

        btnShowPresInfos.setText("SHOW MY PRESCRIBE INFORMATIONS");
        btnShowPresInfos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowPresInfosActionPerformed(evt);
            }
        });

        btnExit.setText("EXIT FROM MY ACCOUNT");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout patientPanelLayout = new javax.swing.GroupLayout(patientPanel);
        patientPanel.setLayout(patientPanelLayout);
        patientPanelLayout.setHorizontalGroup(
            patientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patientPanelLayout.createSequentialGroup()
                .addGroup(patientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(patientPanelLayout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jLabel5))
                    .addGroup(patientPanelLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(patientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(patientPanelLayout.createSequentialGroup()
                                .addGroup(patientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelName)
                                    .addComponent(labelEmail)
                                    .addComponent(labelPass)
                                    .addComponent(labelGender))
                                .addGap(59, 59, 59)
                                .addGroup(patientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(labelNameData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelEmailData, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                                    .addComponent(labelPassData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelGenderData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(patientPanelLayout.createSequentialGroup()
                                .addGroup(patientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(patientPanelLayout.createSequentialGroup()
                                        .addComponent(labelId)
                                        .addGap(69, 69, 69)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(labelAge))
                                .addGap(18, 18, 18)
                                .addGroup(patientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelAgeData, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelIdData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, patientPanelLayout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addGroup(patientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, patientPanelLayout.createSequentialGroup()
                        .addComponent(womanIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85)
                        .addComponent(menIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, patientPanelLayout.createSequentialGroup()
                        .addComponent(btnShowPresInfos)
                        .addGap(109, 109, 109))))
        );
        patientPanelLayout.setVerticalGroup(
            patientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patientPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(patientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(womanIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnShowPresInfos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(patientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelName)
                    .addComponent(labelNameData, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(patientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEmail)
                    .addComponent(labelEmailData, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(patientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPass)
                    .addComponent(labelPassData, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(patientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelGender)
                    .addComponent(labelGenderData))
                .addGap(26, 26, 26)
                .addGroup(patientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelId)
                    .addComponent(labelIdData))
                .addGap(24, 24, 24)
                .addGroup(patientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAge)
                    .addComponent(labelAgeData))
                .addGap(69, 69, 69)
                .addComponent(btnExit)
                .addGap(725, 725, 725)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.add(patientPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//popup menünün tıkladığım yerde görünmesini sağladım.
    private void patientPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_patientPanelMouseClicked
        // TODO add your handling code here:
        jPopupMenu1.setVisible(true);
        jPopupMenu1.show(this, evt.getX(), evt.getY());

    }//GEN-LAST:event_patientPanelMouseClicked
//Main page sayfasını açmasını sağladım.
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        MainPage main = new MainPage();
        main.setVisible(true);

    }//GEN-LAST:event_jMenuItem1ActionPerformed
//Hastanın kendi randevu bilgilerini görebilmesi için oluşturduğum dialogu açtım. 
    private void btnShowPresInfosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowPresInfosActionPerformed
patientsPrescribeInfos.setVisible(true);patientsPrescribeInfos.setBounds(0,0,700,700);    }//GEN-LAST:event_btnShowPresInfosActionPerformed

//Girilen metin ile tablo üzerinden dinamik arama sağladım.
    private void txtSearchDynamicKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchDynamicKeyReleased
        // TODO add your handling code here:
        String search = txtSearchDynamic.getText();
        search(search);
    }//GEN-LAST:event_txtSearchDynamicKeyReleased
//Enter sayfasını açtım ve bu sayfayı da kapatarak sayfadan çıkış yapmasını sağladım.
    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        Enter enter = new Enter();
        enter.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnExitActionPerformed
//Tablodan tıklanan reçete bilgisini listeye aktararak hastanın 
    //daha rahat şekilde reçete bilgisini incelemesini sağladım.
    private void prescribeInfosTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prescribeInfosTableMouseClicked
        // TODO add your handling code here:
        list1.clear();
        int selectedRow = prescribeInfosTable.getSelectedRow();
        String ınfo = "-MEDİCİNE USİNG TYPE- " + prescribeInfosTable.getValueAt(selectedRow, 0) + " -MY MAİL- " + prescribeInfosTable.getValueAt(selectedRow, 1) + " -MEDİCİNE- " + prescribeInfosTable.getValueAt(selectedRow, 2) + " -Barcod- " + prescribeInfosTable.getValueAt(selectedRow, 3);
        list1.addElement(ınfo);
    }//GEN-LAST:event_prescribeInfosTableMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Patient().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnShowPresInfos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelAge;
    private javax.swing.JLabel labelAgeData;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelEmailData;
    private javax.swing.JLabel labelGender;
    private javax.swing.JLabel labelGenderData;
    private javax.swing.JLabel labelId;
    private javax.swing.JLabel labelIdData;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelNameData;
    private javax.swing.JLabel labelPass;
    private javax.swing.JLabel labelPassData;
    private javax.swing.JLabel labelSearch;
    private javax.swing.JList<String> listInfo;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel menIcon;
    private javax.swing.JPanel patientPanel;
    private javax.swing.JDialog patientsPrescribeInfos;
    private javax.swing.JTable prescribeInfosTable;
    private javax.swing.JTextField txtSearchDynamic;
    private javax.swing.JLabel womanIcon;
    // End of variables declaration//GEN-END:variables
}
